spring:
  datasource:
    url: jdbc:mysql://localhost:3307/petPI?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

bucket:
  name: resqpet-images
  accessKey: AKIAUNATVL73O6WMC3XO
  secretKey: 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
  url: https://resqpet-images.s3.us-east-1.amazonaws.com

resqpet:
  app:
    module-name: ResQPet
    api-version: 1.0.0

server:
  ssl:
    key-alias: spring-https
    key-store: classpath:backend.p12
    key-store-type: PKCS12
    key-password: password
  error:
    include-message: always
  port: 8081


security:
  oauth2:
    resource-server:
      jwt:
        jwk-set-uri: https://34.229.216.23:8443/realms/kc-resqpet-auth/protocol/openid-connect/certs
