spring:
  datasource:
    url: jdbc:mysql://db.ctd.academy:3306/pi21023c01_GRUPO7?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: pi21023c01_GRUPO7
    password: PeiQu3ki
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

resqpet:
  app:
    module-name: ResQPet
    api-version: 1.0.0
    
server:
  error:
    include-message: always
