spring:
  datasource:
    url: jdbc:mysql://localhost:3307/petPI?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

resqpet:
  app:
    module-name: ResQPet
    api-version: 1.0.0


aws:
  s3:
    bucket: System.getenv("BUCKET_NAME");
  access_key_id: System.getenv("S3_SECRET_ACCESS_KEY");
  secret_access_key: System.getenv("S3_ACCESS_KEY_ID");
    
server:
  error:
    include-message: always
