spring:
  datasource:
    url: jdbc:mysql://localhost:3307/petPI?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

server:
  error:
    include-message: always
