spring:
  datasource:
    url: jdbc:mysql://localhost:3307/petPI?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

resqpet:
  app:
    module-name: ResQPet
    api-version: 1.0.0


aws:
  s3:
    bucket: s3imagesgittravel
  access_key_id: AKIA3KHN6FDEQCQKUO47
  secret_access_key: 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
    
server:
  error:
    include-message: always
