spring:
  datasource:
    url: jdbc:mysql://localhost:3307/petPI?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect


bucket:
  name: ${BUCKET_NAME}
  accessKey: ${S3_ACCESS_KEY_ID}
  secretKey: ${S3_SECRET_ACCESS_KEY}

resqpet:
  app:
    module-name: ResQPet
    api-version: 1.0.0

server:
  error:
    include-message: always
  port: 8081