spring:
  datasource:
    url: jdbc:mysql://db.ctd.academy:3306/${BACKEND_DB}?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: ${BACKEND_USERNAME}
    password: ${BACKEND_PASSWORD}

bucketName: ${BUCKET_NAME}
accessKey: ${S3_ACCESS_KEY_ID}
secretKey: ${S3_SECRET_ACCESS_KEY}
endpointUrl: https://${BUCKET_NAME}.s3.us-east-1.amazonaws.com

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect


resqpet:
  app:
    module-name: ResQPet
    api-version: 1.0.0

server:
  error:
    include-message: always

