spring:
  datasource:
    url: jdbc:mysql://localhost:3307/petPI?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect


bucket:
  name: ${BUCKET_NAME}
  accessKey: ${S3_ACCESS_KEY_ID}
  secretKey: ${S3_SECRET_ACCESS_KEY}
  url: https://${BUCKET_NAME}.s3.us-east-1.amazonaws.com

resqpet:
  app:
    module-name: ResQPet
    api-version: 1.0.0

server:
  error:
    include-message: always
  port: 8081


security:
  oauth2:
    resource-server:
      jwt:
        jwk-set-uri: https://34.229.216.23:8443/realms/kc-resqpet-auth/protocol/openid-connect/certs
