spring:
  datasource:
    url: jdbc:mysql://localhost:3307/petPI?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

resqpet:
  app:
    module-name: ResQPet
    api-version: 1.0.0
    
server:
  port: 8081
  error:
    include-message: always
