spring:
  datasource:
    url: jdbc:mysql://db.ctd.academy:3306/${BACKEND_DB}?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: ${BACKEND_USERNAME}
    password: ${BACKEND_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect


bucket:
  name: ${BUCKET_NAME}
  accessKey: ${S3_ACCESS_KEY_ID}
  secretKey: ${S3_SECRET_ACCESS_KEY}
  url: https://${BUCKET_NAME}.s3.us-east-1.amazonaws.com

resqpet:
  app:
    module-name: ResQPet
    api-version: 1.0.0

server:
  error:
    include-message: always
  port: 8080

security:
  oauth2:
    resource-server:
      jwt:
        jwk-set-uri: https://34.229.216.23:8443/realms/kc-resqpet-auth/protocol/openid-connect/certs

dh:
  keycloak:
    serverUrl: https://34.229.216.23:8443/
    username: admin
    password: admin
    realm: kc-resqpet-auth
    realmMaster: master
    clientId: admin-cli